server:
  port: 9000
  
eureka:
  instance:
    hostname: localhost
spring:
  application:
    name: ipl-gateway
  cloud:
   gateway:
     routes:
     - id: matchup-service
       uri:  lb://matchup-service
       predicates:
           - Path=/match/
     - id: game-service
       uri:  lb://game-service
       predicates:
           - Path=/game/
      
      