INSERT INTO COUNTRY VALUES(1,'KOLKATA KNIGHT RIDERS');
INSERT INTO COUNTRY VALUES(2,'ROYAL CHALLENGERS BANGALORE');
INSERT INTO COUNTRY VALUES(3,'MUMBAI INDIANS');
INSERT INTO COUNTRY VALUES(4,'CHENNAI SUPER KINGS');
INSERT INTO COUNTRY VALUES(5,'SUNRISERS HYDERABAD');



INSERT INTO PLAYERS VALUES(1,'DAVID WARNE',5);
INSERT INTO PLAYERS VALUES(2,'GAUTAM GAMBHIR',1);
INSERT INTO PLAYERS VALUES(3,'ROHIT SHARMA',3);
INSERT INTO PLAYERS VALUES(4,'MS DHONI',4);